// Public API of the engine (pure functions + the React glue in useDerivedRun).
export { deriveRun, withTrialBalance } from './derive/deriveRun'
export { deriveItems, itemEntries } from './derive/items'
export { deriveAttention, sortAttention } from './derive/attention'
export { synthesizeEvents } from './derive/events'
export { computeStats } from './derive/stats'
export { compareTrialBalance } from './ledger/trialBalance'
export { effectiveDeliverables, entryImbalance } from './ledger/entries'
export { validateDeliverables } from './validate/validate'
export { scoreRun, scoreTotals } from './score/score'
export { diffItems } from './score/itemDiff'
export { jeMatchDetail, type NormLine } from './score/primitives'
export { apItemId, arBillingItemId, arCashItemId, bankAccountItemId, bankItemId, closeItemId, icItemId, parseItemId, rowKey } from './ids'
export { useActiveRun, useAttention, useDerivedRun, useItem, useItemEvents, type DerivedRunState } from './useDerivedRun'
