"""Ports: everything the use cases need from the outside world.

``PhaseRepository`` is the seam for swapping the in-memory store for a database: its
methods are domain questions ("balances for company X"), not file or table names.
"""
from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Any, Protocol

from ..ledger import Ledger
from ..model import Manifest, ValidationContext
from .types import Job, LoadReport, Meta, PackageRecord, PhaseSummary

Row = dict[str, Any]
Filters = Mapping[str, Any]


class PhaseRepository(Protocol):
    # loading
    def load_phase(self, package_id: str, phase_dir: Path, manifest: Manifest) -> LoadReport: ...
    def mark(self, phase: str, package_id: str, status: str) -> None: ...
    # catalogue
    def phases(self) -> list[PhaseSummary]: ...
    def phase(self, phase: str) -> PhaseSummary: ...
    def location(self, phase: str) -> Path: ...
    def meta(self, phase: str, sources: list[str]) -> Meta: ...
    # master data and inputs
    def records(self, phase: str, collection: str, filters: Filters) -> list[Row]: ...
    def record(self, phase: str, collection: str, record_id: str) -> Row: ...
    def tasks(self, phase: str) -> dict[str, Any]: ...
    def documents(self, phase: str, kind: str | None) -> list[Row]: ...
    def attachments(self, phase: str, doc_id: str) -> list[Row]: ...
    def policies(self, phase: str) -> Row: ...
    # accounting
    def journal_entries(self, phase: str, filters: Filters) -> list[Row]: ...
    def journal_entry(self, phase: str, entry_id: str) -> Row: ...
    def journal_lines(self, phase: str, filters: Filters) -> list[Row]: ...
    def balances(self, phase: str, filters: Filters) -> list[Row]: ...
    def balance_summary(self, phase: str, company: str | None) -> list[Row]: ...
    def open_items(self, phase: str, filters: Filters) -> list[Row]: ...
    def ledger_projection(self, phase: str) -> Ledger: ...
    def validation_context(self, phase: str) -> ValidationContext: ...
    # bank and fx
    def bank_accounts(self, phase: str, company: str | None) -> list[Row]: ...
    def bank_lines(self, phase: str, account: str, filters: Filters) -> list[Row]: ...
    def fx_rates(self, phase: str, filters: Filters) -> list[Row]: ...
    def fx_rate_at(self, phase: str, currency: str, day: str) -> Row: ...


class PackageStore(Protocol):
    def get(self, package_id: str) -> PackageRecord | None: ...
    def list(self) -> list[PackageRecord]: ...
    def register(self, archive: Path, package_id: str) -> Manifest: ...
    def manifest(self, package_id: str) -> Manifest: ...
    def root(self, package_id: str) -> Path: ...


class JobStore(Protocol):
    def create(self, package_id: str) -> Job: ...
    def update(self, job_id: str, **fields: Any) -> Job: ...
    def get(self, job_id: str) -> Job: ...
    def active(self) -> Job | None: ...
    def latest_for(self, package_id: str) -> Job | None: ...
    def restore(self, job: Job) -> None: ...


class RunStore(Protocol):
    def list(self) -> list[Row]: ...
    def get(self, run_id: str) -> Row: ...
    def files_root(self, run_id: str) -> Path: ...
    def events(self, run_id: str) -> list[Row]: ...
    def attention(self, run_id: str) -> list[Row]: ...
    def overrides(self, run_id: str) -> list[Row]: ...
    def add_override(self, run_id: str, row: Row) -> None: ...


class SubmissionStore(Protocol):
    def directory(self, phase: str) -> Path: ...
    def files(self, phase: str) -> dict[str, dict[str, Any]]: ...
    def rows(self, phase: str, module: str) -> list[Row]: ...


class SubmissionChecker(Protocol):
    """Structure check of delivery rows. Needs no golden, so it lives on the solver side."""

    def check(self, rows_by_module: Mapping[str, list[Row]]) -> list[Row]: ...


class LandingCatalog(Protocol):
    """Normalized document/bank landing tables (DuckDB). Optional: needs the ``landing`` extra."""

    @property
    def available(self) -> bool: ...
    def tables(self) -> list[str]: ...
    def counts(self, package_id: str, phase: str, phase_dir: Path) -> dict[str, int]: ...
    def rows(self, package_id: str, phase: str, phase_dir: Path, table: str, criteria: Mapping[str, Any]) -> list[Row]: ...


class EvaluationGateway(Protocol):
    """Evaluator side. Implemented inside ``kalmora.evaluation`` so that solver modules
    never import it (ADR 0001)."""

    @property
    def enabled(self) -> bool: ...
    def evaluate(self, phase: str, phase_dir: Path, submission_dir: Path) -> Row: ...
