from typing import NotRequired, Required, TypedDict

from .scalars import AccountCode, CompanyCode, Cents, Currency, DocCents, PartnerCode


class JournalLine(TypedDict, total=False):
    """One debit or credit on one account: the atom of the double-entry book.

    ERP shape of ``erp/journal_entries.jsonl``. Only ``account``, ``debit`` and
    ``credit`` are essential to the ledger; ``company``, ``line`` and ``book_line``
    are filled in on normalization, and the dimensions below may be absent on
    solver adjustments (delivery files compare lines by account, partner, cost
    object and amount, within +/-2 cents).

    A line is *signed by structure*, not by sign: debit and credit are both
    non-negative and at most one is positive. The balance contribution of a line is
    ``debit - credit``, so liabilities and income accumulate as negatives.
    """

    account: Required[AccountCode]
    """Eight-digit ledger account. Decides which other fields are mandatory:
    open-item accounts need ``partner``; expense, income and fixed-asset accounts need
    a cost object."""

    debit: Required[Cents]
    """Debit (*debe*) in local currency, in cents. Non-negative; zero on a credit line."""

    credit: Required[Cents]
    """Credit (*haber*) in local currency, in cents. Non-negative; zero on a debit line.
    A line cannot carry both ``debit`` and ``credit``."""

    line: int
    """Position inside the entry (1-based, unique). Assigned by order when missing; together
    with the entry ``id`` it forms ``book_line``, the reference bank reconciliation uses."""

    company: CompanyCode
    """Company of the line; must equal the entry's company (an entry never spans companies).
    Inherited from the entry when missing."""

    currency: Currency
    """Document currency of this line. Differs from the entry's currency for foreign-currency
    lines (USD/GBP invoices, or EUR items in the Mexican company)."""

    amount_doc: DocCents
    """Amount in document currency, unsigned. In local currency it equals ``max(debit, credit)``;
    in a foreign currency it preserves the original invoiced amount while ``debit``/``credit``
    carry the conversion at the invoice-date SYN-BCE rate. Needed later to revalue
    monetary items at close (``FX_REVAL``)."""

    partner: PartnerCode | None
    """Sub-ledger partner. Mandatory on open-item accounts, where it names the vendor,
    customer, group company or factor (see ``PartnerCode``); ``None`` elsewhere. It is part
    of the open item's identity: the same invoice with another partner is a different item."""

    assignment: str | None
    """Reference tying the item to its source document or to the document that clears it:
    invoice number, ``purchase order/position`` (``4500022284/10``), receipt number,
    ``PAG<number>`` for promissory notes. It is what lets a payment *find* the invoice it
    settles. It is not bank reconciliation, which links statement lines to 572 postings."""

    cost_center: str | None
    """Cost center (*centro de coste*): where overhead and service costs/revenue go. Used in
    structure and services; mutually exclusive with ``wbs`` (policy §1)."""

    wbs: str | None
    """Construction WBS element (*PEP*, e.g. ``OB-1100-2514.04``): the work package a cost or
    revenue belongs to. Used on construction jobs; mutually exclusive with ``cost_center``."""

    tax_code: str | None
    """VAT treatment of the line (``S21`` 21 %, ``R10`` 10 %, ``SISP`` construction reverse
    charge, intra-EU, exempt...). Drives the VAT lines (472/477) that accompany it."""

    text: str
    """Free text. Informational: plays no part in balances, matching or validation."""

    book_line: NotRequired[str]
    """Derived reference ``<entry id>#<line>`` (``1100-2024-5000000006#2``). Generated by the
    ledger, absent from the ERP. This is how bank reconciliation points at a posting in 572.
    Only assigned to entries that have an ``id``."""
